### ISSUE TITLE
A better target to patch: libmacgpg.framework

### ISSUE THREAD

**Issue by xcvista** [GpgMailNoActivation/GpgMailNoActivation#2]
I have audited the sources, and it appeared to me that all the license stuff is done in `libmacgpg.framework`, not `GPGMail.mailbundle`.

I have a fork for that library that have the license checks stubbed out. So far on my own computer it is working.

Fork is here: https://github.com/xcvista/Libmacgpg

**Comment by GpgMailNoActivation** [comment]
I just did the minimum changes needed to get it working. I didn't attempt to remove the DRM code, just circumvent it.
