### ISSUE TITLE
GPG Suite 2019.1 August 22nd, 2019 - Supported?

### ISSUE THREAD

**Issue by hevisko** [GpgMailNoActivation/GpgMailNoActivation#3]
Just saw that GPG Suite 2019.1 August 22nd, 2019, is released.

Will the 2018.5 fixes work for it too?

**Comment by GpgMailNoActivation** [comment]
I have made a new version that patches the 2019.1_83 version. It is released here: https://github.com/GpgMailNoActivation/GpgMailNoActivation/releases/tag/Ver_2019.1_83
